### ISSUE TITLE
Possibility to use executables or Python based Checker Bundles and Report Modules from Checker Libraries

### ISSUE THREAD

**Issue by andreaskern74** [asam-ev/qc-framework#11]
**Is your feature request related to a problem? Please describe.**

Currently the Checker Bundle and Report Module binaries need to be placed into the `bin` folder of the framework, because the original architecture does not consider separation of framework and specific Checker Libraries. It is not possible to use Checker Bundles and Report Modules executables (or Python scripts) from other Checker Libraries.

In the the sub-group meeting of 2024/02/19 we decided that the framework shall support directly calling Python based modules. Currently only binary executable are possible.

**Describe the solution you'd like**

Possibility to include/call Checker Bundle and Report Module binaries and Python scripts from arbitrary paths from the framework installation directory. Adaptions necessary in
* Configuration format --> include directory information for the included modules
* Configuration GUI --> to determine available Checkers and their parameters
* Runtime --> call the Checker Bundle and Report Module executables / Python scripts, based on the configuration

**Comment by MatteoRagni** [comment]
I think we should take into consideration a format for a *manifest* file (text based data, like yaml or json).

Framework can load manifest from a list of path (like OS `PATH` env variables).

**Comment by MatteoRagni** [comment]
I want to exapnd what we discussed briefly in a meeting yesterday morning.

## Manifests

Manifests should be files or function calls results that allows the framework to understand features for a checker bundle.

From an implementation point of view, I usually prefer to have manifest that results from a function call, so that implementers may decide to create programmatically the information that is contained. However, the mainfest shall include at least:

 * manifest protocol version
 * executable version
 * executable metadata (author, description, the usual suspects)
 * the arguments description
 * the checker bundles included
 * the rules checked
 
Please notice that the manifest shall be in a parsable format, such as `json` or `yaml`. I usually prefer to force the usage of a subset of `yaml` that is `json` compatible through [json schema rules](https://json-schema.org/understanding-json-schema/reference).

> It should be clear that it is possible to get the best of both world using **thin** manifests: manifests that provide just enough information to query the checker library for the full version of the manifest[^3]. This is important to allow the Checker Libraries to programmatically create the full manifest content. This is usually a solution that permits the Library developer to reduce maintenance and errors. We should take into consideration this.

With the draft format proposed we have manifests for Checker Libraries, that may contain one or more checker bundles, which have one or more rule check.

Regarding distribution of manifests there are different approaches, which can be used alternatively or together:

 * _directory_ centric. A directory exists for aggragating manifest in a unique location[^1]. Iniside this configuration directory we can have an additional directory `manifests.conf.d` (e.g., on Linux it can be `/etc/qc4openx/manifests.conf.d`) that may contain one or more manifest for the different bundle libraries. Active manifest have a name with a well defined extension (usually `.conf`). If the extension does not match, the manifest is not parsed. This approach works really well for stable installation (i.e., user workstation)
 * _env var_ centric, meaning it exists an env variable (e.g.: `ASAM_QC4OPENX_PATHS`) which is a path-sep[^2] collection of path in which manifests file must be searched. Manifests must match a specific rule (e.g., having a specific name or having a specific extension). The approach mimics what is normally done for system `PATH`
 
[^1]: on Linux this is a subdirectory of `/etc`, on Windows this is usually in `AppData` or in installation directory
[^2]: On Unix this is the `:` character. On Windows this is the `;` character.
[^3]: In our project that can be running the checker library with a very specific option (e.g., `--manifest`)

## Running checker library

> Disclaimer: I should study a little more the existing code, lets take it as a philosophical discussion since as far as I can iunderstand this part is still not fully implemented in QC4OpenX.

There are several approaches that we can be followed to run a checker library, and they depend on the technologies used. Ideally we should select a solution that encopass all the possible scenario in a unique and reasonable way, without constraining to much the checker developer. I'll try to create some sort of solution matrix for the main scenarios.

 * Python Framework and Python Checker Library:
    * import library in same process
       * using `importlib` functionalities, at least the checker install path must be included in current process `sys.path`. A standard entrypoint interface should be defined. Scheduling can be perfomed with something like `threading.ThreadPooler`. No real concurrency (GIL). There is no real separation between framework and checker interpreter state. This makes communications between the two extremely easy, but may leave the door open to unwanted framework state modifications made by a checker. 
    * running as forked process
       * at least the checker must be included in current process `sys.PATH`. A standard entrypoint interface shold be defined. using `multiprocessing.pool` it is possible to schedule the execution of the entrypoint based upon resource. In this case there is a stricter coupling between interpreter and checker libraries, with respect to a new shell process (at least on Linux). As long as exchenged object are pickable, communication is straightforward, and it is difficult for a checker to modify framework state.
    * running as a new shell process (**with a new interpreter**)
       * the checker library is bundled with an interpreter using tools like [`nuitka`](https://nuitka.net/doc/user-manual.html#use-case-4-program-distribution) or similar as standalone executable that can be runnned as a program starting from a command line string using `subprocess`.
       * the checker library informs via manifest that should be run using a python interpreter, wich is run via `subprocess`. Entrypoint may be specified in terms of python packaging (`console_entrypoint` in `setup.py` or `__main__.py` module file). This approach is valid also if the checker library is implemented using a different interpreted language, the manifest should provide the name of interpreter executable to use.
    
 * Python Framework and Exported C interface Checker Library:
    * import library in same process
       * the C interface must be predefined. The Checker Library can be used as a python library by creating a FFI python layer that does a `dlopen` on then checker library. The FFI layer is part of the framework and shared among all the Checker Library implemented with this strategy
    * running as a forked process
       * the checker library shall implement a `main` entrypoint and the framework run it as `subprocess`. This approach is more or less independent with respect to the language used in the implementation of the checker library.
    * running as a new shell process
       * same as forked process
    
 * Python Framework and C/C++ Checker Library:
    * import library in the same process
       * The checker library may expose itself as a library using [`pybind11`](https://github.com/pybind/pybind11). This interface can be made optional with a dynamic linkage distribution. The `pybind11` interface should respect a predefined python interface. It is exactly the same as having a python framework with a python library.
    * importing as a forked process
       * the checker library shall implement a `main` entrypoint and the framework run it as `subprocess`. This approach is more or less independent with respect to the language used in the implementation of the checker library.
    * running as a new shell process with an new interpreter
       * same as forked process

 * C/C++ Framework and Python Checker Library:
    * import library in same process
       * the framework may spawn a python interpreter inside its process. This can be done by directly importing `libpython` or having `pybind11` to handle the interpreter inside the checker. The included interpreter loads the checker library exactly like in the Python Framework and Python Checker Library case. A thin layer should be implemented to convert raw data in python data.
    * running as forked process
       * same as before to include an interpreter, but the framework runs libraries from the interpreter using `multiprocessing.pool`
       * the checker is started as a new executable that includes a python interpreter to run the library. This solution is an halfway between a couple of approaches we have seen before.
    * running as a new shell process with a new interpreter
       * same as the second solution of running in a forked process
    
 * C/C++ Framework and Exported C interface or C++ Library:
    * import library in same process
       * C++ FFI interfaces run in the same process with a `dlopen` of the checker library. This approach can be done in two ways:
          * the framework provides guidance about the C interface to export and the bundle must respect that interface
          * the framework provide an integration library that checker-lib developer must use and link to implement a _plugin_ of the framework. This reduces the amount of work to be done for checker developer, while framework developer must maintain the plugin library. Must be noticed that the internally the plugin system must implement a C exported interface for ABI stability.  
    * running as a forked process
       * the checker library expose a `main` entrypoint and it is run as a standalone application
    * running as a new shell process
       * same as before

**Comment by andreaskern74** [comment]
@MatteoRagni : Some information about the current architecture/implementation...  

A Checker Bundle is always an own executable (Windows: .exe, Linux "x-flag"). When you add an own Checker Bundle to the configuration, then you have directly to select the executable. (I noticed that the image in documentation is outdated 🙈). 

The configuration GUI then calls this executable in an own process and it writes out a standard report file containing all included Checkers with their parameters, but without any found issues/locations --> "empty" report file, but containing all configuration data for this Checker Bundle. So the result file is somehow also the manifest for this Checker Bundle (not for the whole Checker Library). Especially when we add the addressed rules and meta data.... If there is no result file, then it is a Report Module. I think that was the criteria, but not 100% sure.

When we started, I thought that we simply should add the possibility to add instead an executable also a `.py` file. And this contains a main function, which evaluates the same command line parameters and handling as normal executables. 

We have still one high-level requirement that everybody can bring in their own Checker Bundles and select from any programming language.

But yes, let's discuss if/how the architecture benefit from a manifest file for Checker Libraries and how the Python-based Checker Bundles are called.

**Comment by ClemensLinnhoff** [comment]
What is the status on this? Is it already possible to use a python based checker bundle without making it into an executable?

**Comment by hoangtungdinh** [comment]
Hi @ClemensLinnhoff, currently it is possible to use a Python based checker bundle without making it an executable by using a workaround: Define a bash script as an entry point executable and include it in the framework. An example bash script can be found [here](https://github.com/asam-ev/qc-framework/blob/develop/demo_pipeline/xoscBundle).

This is only a temporary solution until the above manifest file is supported.

**Comment by andreaskern74** [comment]
This feature is implemented :-) We should close this one --> CCB.
