### ISSUE TITLE
Not possible to navigate the map in the 3D Esmini viewer

### ISSUE THREAD

**Issue by AsamDiegoSanchez** [asam-ev/qc-framework#180]
**Is your feature request related to a problem? Please describe.**
Right now it is not possible to navigate through the 3D representation in the Esmini Viewer plugin. The coordinates are fixed to the pole (marker) and it is only possible to zoom-in/out from that point.

**Describe the solution you'd like**
It could be great if the user could navigate across the visualisation, zooming-in/out other parts of the map. 

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by andreaskern74** [comment]
Not sure, because I have not tested it, and I'm not an esmini user.... but esmini visualization is based on the Open Scene Graph viewer. And I think the default camera "look at" in esmini is locked on the object (the pole in our case). I think there is the possibility to switch the camera mode (to free flying or similar) with a keyboard short cut. See esmini doc or press "H"

So, this is more a "need-to-know" or probably documentation issue.

But if user change the camera mode in esmini, then our plugin probably need to reset the camera mode to the one we need on clicking on the next location, that the camera is moving in emini. This need to be tested/evaluated to ensure a good workflow.

In our visualization, the user can also switch the mode no navigate. The plugin resets the camera mode when selecting another issue.

**Comment by andreaskern74** [comment]
I think this is done --> CCB

**Comment by AsamDiegoSanchez** [comment]
[like]  Diego SANCHEZ LAZARO (ASAM) reacted to your message:
________________________________
